default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: dima
  password: fuckme420

development:
  <<: *default
  database: internship_development

test:
  <<: *default
  database: internship_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>